#!/usr/bin/env python3
"""Bundle config/*.json assumption sets into data/assumptions.js (+ copy raw JSON).

The front end loads a plain <script> so it works from a local file as well as
from GitHub Pages (fetch() of local JSON is blocked by browsers on file://).

Set order and labels come from config/sets.json:
  [{"id": "v2", "file": "assumptions_v2.json", "label": "...", "default": true}, ...]
"""
import json, os, shutil, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CFG = os.path.join(ROOT, "config"); OUT = os.path.join(ROOT, "data")

def main():
    os.makedirs(OUT, exist_ok=True)
    sets = json.load(open(os.path.join(CFG, "sets.json")))
    bundle = []
    for s in sets:
        path = os.path.join(CFG, s["file"])
        data = json.load(open(path))
        shutil.copy(path, os.path.join(OUT, s["file"]))
        bundle.append({"id": s["id"], "label": s["label"], "default": s.get("default", False), "data": data})
    with open(os.path.join(OUT, "assumptions.js"), "w") as f:
        f.write("// generated by src/model/build_web.py — do not edit by hand\n")
        f.write("window.ASSUMPTION_SETS=" + json.dumps(bundle, separators=(",", ":")) + ";\n")
    print(f"wrote {len(bundle)} sets to data/assumptions.js")

if __name__ == "__main__":
    main()
